<?php
define('_DB_SERVER_', 'localhost');
define('_DB_NAME_', 'audiorms');
define('_DB_USER_', 'root');
define('_DB_PASSWD_', 'root');
define('_DB_PREFIX_', 'ps_');
define('_MYSQL_ENGINE_', 'InnoDB');
define('_PS_CACHING_SYSTEM_', 'CacheXcache');
define('_PS_CACHE_ENABLED_', '1');
define('_MEDIA_SERVER_1_', '');
define('_MEDIA_SERVER_2_', '');
define('_MEDIA_SERVER_3_', '');
define('_PS_DIRECTORY_', '/');
define('_COOKIE_KEY_', 'hNaBX0Mr3ZGIes7mRDJ0yoQ431XcWNBPL2rvemyX1bKnnM0po72APpFB');
define('_COOKIE_IV_', 'ZZbX3yYp');
define('_PS_CREATION_DATE_', '2012-06-14');
define('_PS_VERSION_', '1.6.0.6');
define('_RIJNDAEL_KEY_', 'OG1uZtd45MiwRE8rzNUdA0EQhWHJhm47');
define('_RIJNDAEL_IV_', 'tZb0roYZuDbPQUmIGLbrDA==');
